name: Build, Run and Finalize Deploy

on:
  push:
    branches:
      - develop
      - main

jobs:
  deploy-on-vps:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            # Arrêter tous les conteneurs s'ils existent
            containers=$(sudo docker ps -q)
            if [ -n "$containers" ]; then
              sudo docker stop $containers
            fi

            # Supprimer tous les conteneurs s'ils existent
            containers=$(sudo docker ps -a -q)
            if [ -n "$containers" ]; then
              sudo docker rm $containers
            fi

            # Vérifier si le répertoire existe, sinon le cloner
            if [ ! -d ~/dockerhub_test/ ]; then
              mkdir -p ~/dockerhub_test
              git clone --branch develop ${{ secrets.REPO_GIT }} ~/dockerhub_test/
            else
              cd ~/dockerhub_test/
              # Réinitialiser les changements locaux à l'état de la branche distante
              git fetch origin
              git reset --hard origin/develop
            fi

  build-and-run-on-vps:
    runs-on: ubuntu-latest
    needs: deploy-on-vps

    steps:
      - name: Build Docker Containers
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd ~/dockerhub_test/
            sudo docker-compose down
            sudo docker-compose build --parallel

      - name: Start Docker Containers
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd ~/dockerhub_test/
            sudo  docker-compose up -d
